git:
  depth: 1
language: "node_js"
node_js:
  - "10"
  - "11"
install:
  - "npm ci"
cache: npm
script:
  - "npm run build"
  - "npm test"
notifications:
  email:
    on_success: "change"
    on_failure: "always"
